resources:
  - repo: self
queue:
  name: Hosted VS2017
trigger:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - Espresso-v8-BuildScheduler/*
    exclude:
      - Espresso-v8-BuildScheduler/README.md
pr:
  branches:
    include:
      - master
      - releases/*
  paths:
    include:
      - Espresso-v8-BuildScheduler/*
    exclude:
      - Espresso-v8-BuildScheduler/README.md
steps:
  - task: NuGetToolInstaller@0
    displayName: "Use NuGet 4.4.1"
    inputs:
      versionSpec: 4.4.1

  - task: NuGetCommand@2
    displayName: "NuGet restore"
    inputs:
      feedsToUse: "select"
      includeNuGetOrg: true
      restoreSolution: "$(System.DefaultWorkingDirectory)/Espresso-v8-BuildScheduler/Espresso-v8-BuildScheduler.csproj"

  - task: VSBuild@1
    displayName: "Build solution"
    inputs:
      solution: "$(System.DefaultWorkingDirectory)/Espresso-v8-BuildScheduler/Espresso-v8-BuildScheduler.csproj"
      msbuildArgs: '/p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl="$(Agent.TempDirectory)\WebAppContent\\"'
      platform: "any cpu"
      configuration: "release"

  - task: ArchiveFiles@2
    displayName: "Archive Files"
    inputs:
      rootFolderOrFile: '$(Agent.TempDirectory)\WebAppContent'
      includeRootFolder: false

  - task: VSTest@2
    displayName: "Test Assemblies"
    inputs:
      testAssemblyVer2: |
        **\release\*test*.dll
        !**\obj\**
      platform: "any cpu"
      configuration: "release"

  - task: PublishSymbols@2
    displayName: "Publish symbols path"
    inputs:
      SearchPattern: '**\bin\**\*.pdb'
      PublishSymbols: false
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact"
    inputs:
      PathtoPublish: "$(build.artifactstagingdirectory)"
      ArtifactName: "Espresso-v8-BuildScheduler"
